/* eslint-disable react/no-unescaped-entities */
import React, { useState } from "react";
import DefaultLayout from "@/components/Layouts/defaultLayout";
import { Select } from "antd";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

const ContactUs = () => {
  const [loading, setloading] = useState(false);
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <DefaultLayout>
        <main className="">
          <section className="w-full bg-default dark:bg-gray-900 min-h-screen">
            <div className="max-w-screen-xl mx-auto w-full p-10">
              <h1 className="text-center text-4xl font-extrabold tracking-tight leading-none md:text-5xl dark:text-white md:pr-20">
                About Us
              </h1>
              <p className="text-lg pt-10">
                OrgPosture provide a platform that enables end-to-end visibility on the security posture of organizations 
                using risk-based approach. Incorporated in 2022, OrgPosture is the only company that provide a customized 
                approach to technology risk management using security frameworks and standards leveraging on data and 
                analytics to provide risk insights to companies.
              </p>

              <div className="text-center w-full md:w-1/2 mx-auto h-[420px] relative mt-10">
                <Image
                  fill
                  className="object-contain w-full mx-auto" 
                  data-aos="fade-zoom-in"
                  data-aos-anchor-placement="top-bottom" data-aos-duration="2000"
                  src="/assets/images/hero_1.svg" 
                  alt="about-us" 
                />
              </div>
            </div>
          </section>

          <section className="w-full bg-white dark:bg-gray-900 min-h-screen">
            <div className="max-w-screen-xl mx-auto w-full p-10">
              <h3 className="text-2xl text-black dark:text-white font-semibold">Our vision</h3>
              
              <p className="leading-relaxed text-black dark:text-white pt-3">
                Transform businesses to become effective and efficient in managing cyber risk.
                <br />
                Our chief aim is to help businesses transform into metrics driven, objective focused organizations to enable fact-based decision making.                
              </p>
              
              <div className="w-full md:w-1/2 h-[286px] mx-auto relative">
                <Image
                  className="object-contain w-full mx-auto" 
                  fill
                  data-aos="fade-zoom-in"
                  data-aos-anchor-placement="top-bottom" data-aos-duration="2000"
                  src="/assets/images/About-Us/vision.png" 
                  alt="mockup" 
                />
              </div>         
     
              <p>
                Security is tough, especially with limited budget and corporate sponsors who are distracted by the day-to-day of running a big company. Through all of this, cybercriminals, we hear over and over again, are lurking just outside the door like hungry possums, ceaselessly testing the window glass for strength and trying to lift the roof tiles as they look for a way to sneak in and wreak havoc under your nose.

                <br />
                <br />
                Our goal is to ensure that businesses are aware about the risk they face through the provision of a comprehensive real time view of their security posture through security integrations and data analytics.
                We care about automating customers cybersecurity processes through the development of Key performance indicators and key risk indicators to ensure proactive risk controls whiles safeguarding the business in achieving its objectives.
              </p>

              <div className="md:py-16 lg:py-20 relative">
                <h3 className="text-2xl text-black dark:text-white font-semibold">Our Values</h3>

                <div className="absolute right-10 -top-2">
                  <Image
                    width={285}
                    height={142}
                    className="object-contain" 
                    data-aos="fade-zoom-in"
                    data-aos-anchor-placement="top-bottom" data-aos-duration="2000"
                    src="/assets/images/About-Us/values.png" 
                    alt="mockup" 
                  />
                </div>

                <div className="flex flex-col leading-relaxed pt-2">
                  <span> 
                    <b><i>Integrity</i></b> - We honor our word and commitment
                  </span>
                  <span> 
                    <b><i>Collaboration</i></b> - We work closely with our clients to understand their unique security needs and challenges whiles staying up-to-date with the latest threats and trends.
                  </span>
                  <span> 
                    <b><i>Customer-focused</i></b> - We prioritize customer's needs and requirements, and tailor our services to meet each client's unique needs. Our aim is to build long-lasting relationships with clients based on trust, communication, and mutual respect.
                  </span>
                  <span> 
                    <b><i>Excellence</i></b> - We aim to exceed expectations.       
                  </span>
                </div>
              </div>
            </div>
          </section>
        </main>
      </DefaultLayout>
    </div>
  );
};

export default ContactUs;
