import React, { useState } from 'react'
import DefaultLayout from '@/components/Layouts/defaultLayout'
import { Select } from 'antd'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

const ConsultingServices = () => {
    const [loading, setloading] = useState(false);
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <DefaultLayout>
        <main className="w-full bg-white dark:bg-gray-900">
            <div className="relative min-h-[60vh]">
                <Image
                    className="object-cover w-full h-full" 
                    fill
                    data-aos="fade-zoom-in"
                    data-aos-anchor-placement="top-bottom" data-aos-duration="2000"
                    src="/assets/images/Consulting/hero.png"
                    alt="mockup" 
                />
            </div>

            <div class="max-w-screen-xl mx-auto px-4 md:p-10 lg:p-16 grid grid-cols-1 sm:grid-cols-12">
                <div className="md:pr-16 xl:pr-24 md:col-span-6" data-aos="fade-left">
                    <h3 className="font-semibold text-2xl">IT Advisory</h3>
                    <ul className="text-xl lg:pl-10 list-disc pb-10">                    
                        <li>IT Governance - COBIT </li>
                        <li>Risk Management Program - COBIT for Risk </li>
                        <li>Capability Maturity Model implementation (CMMI)</li>
                        <li>Information Security Management System - ISO 27001 </li>
                        <li>Quality Management - ISO 9001</li>
                        <li>Business Continuity - ISO 22301</li>
                        <li>HITRUST</li>
                        <li>NIST Framework </li>
                        <li>Risk Management - ISO 31000</li>
                        <li>PCI DSS </li>
                        <li>Security Standards Maturity and enhancement Assessments</li>
                    </ul>

                    <h3 className="font-semibold text-2xl">Audit​</h3>
                    <ul className="lg:pl-10 list-disc text-xl">
                        <li>IS Auditing</li>
                    </ul>                    
                </div>

                <div className="md:col-span-6">
                    <Image
                        width={402}
                        height={402}
                        className="object-contain ml-auto" 
                        src="/assets/images/Consulting/security.png"
                        data-aos="zoom-in" data-aos-duration="1500"
                        alt="team_managment" 
                    />
                </div>
            </div>
        </main>
      </DefaultLayout>
    </div>
  )
}

export default ConsultingServices